### PR TITLE
Switch tracks by swipe on cover

### PR DESCRIPTION
**Pull request by Koitharu**
#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of changes
Simple implementation of swipe gestures support on cover in player.
I can try to implement this feature using Carousel or ViewPager if it is ok

#### Fixes the following issues
#94 

#### Any additional information

https://github.com/OxygenCobalt/Auxio/assets/8948226/2c63d255-a798-4b89-a802-f4a0587312ba

#### APK testing
None yet

#### Due Diligence
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.

### CODE REVIEW

**Comment by OxygenCobalt** [comment]
Wow! This is not what I expected today at all. The implementation looks really good, I just have a few requests with the UX:

First, I'm unsure about how user-friendly this is in the context of the `layout-h480dp` layout. The cover in that layout is *small*, as can be seen below:
image

Skipping by swiping the cover alone would be really hard. Ideally, I think the gesture behavior should become some kind of parent `ViewGroup` that wraps the cover view and the song information within the `layout-h480dp` layout. Otherwise, it can simply wrap the cover in other layouts.

Additionally, I'd like it more if there was some kind of animated gesture indicator. Otherwise, this behavior is a bit mysterious and janky. For example, a circle with a "skip" icon inside it could grow from the end of the view and then highlight once the skip threshold was met. This is a lot like the "Swipe to Refresh" pattern, but just sideways.

There are a few other ideas I've had regarding this, but I can handle those later since they aren't really part of an MVP of #94. If you are having trouble with working on these requests, I'll still be okay with merging it and then filling in the gaps myself.

Great work!

**Comment by OxygenCobalt** [comment]
Just bumping this in the case that the notification for my prior comment didn't go through @Koitharu.

**Comment by Koitharu** [comment]
I can also propose using of ViewPager2 for cover. Pros: user can see previous/next cover art while swiping

**Comment by OxygenCobalt** [comment]
I agree, when I tried to do it once I kept running into this visual bug when reshuffling, but you can try @Koitharu.

**Comment by Koitharu** [comment]
Closed in favor of #503

**Comment by OxygenCobalt** [comment]
Reopening since #503 turned out to not to create high-quality UX.

**Pull request merged**
