### PR TITLE
Fix German translations

### PR DESCRIPTION
**Pull request by qwerty287**
**What is it?**
- [X] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

**Description of changes**

- Fix some wrong German translations
- Add German translation for some strings

**Fixes the following issues**

- none, related to #3 

**Any additional information**

**APK testing** 

[debug.zip](https://github.com/OxygenCobalt/Auxio/files/6867037/debug.zip)

**Due Diligence**

- [X] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md) and [Accepted additions & Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md).

### CODE REVIEW

**Comment by OxygenCobalt** [comment]
Is this translation any specific dialect or general german?

**Comment by qwerty287** [comment]
It's general German

**Comment by OxygenCobalt** [comment]
Okay, looks good then.

**Comment by qwerty287** [comment]
@OxygenCobalt Something went wrong and you undid the merge in this commit: https://github.com/OxygenCobalt/Auxio/commit/cf676120425423ff8c4fc06afc951091f231b4f6#diff-7049c01dbaca09e41462205bc840bb2bdf6766f0b832e1ff68059c7fdfafadc8 
You could just redo it by copying the hole content of the `strings.xml` in `values-de` from this PR (i.e. this file: https://raw.githubusercontent.com/OxygenCobalt/Auxio/44570309ad4ac8cfa97ec17282f063d99639b0ce/app/src/main/res/values-de/strings.xml).

**Comment by OxygenCobalt** [comment]
Hm. Looks like a pull gone wrong. I'll get around to it.

**Comment by OxygenCobalt** [comment]
I think you might want to re-translate the strings instead of re-adding them. I've been working on a major rework and so not only are the labels outdated, but there are also new/removed strings.

**Comment by qwerty287** [comment]
OK, I'll see when I have the time to do this.

**Pull request merged**
