### PR TITLE
convert png files to webp to reduce apk size

### PR DESCRIPTION
**Pull request by connyduck**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [x] Meta improvement to the project (dev facing)

#### Description of changes

- Converted  png files to webp to reduce apk size
- The conversion is lossless, the files look identical
- release apk size before: 6864 kB
- release apk size after: 6806 kB

#### APK testing

debug.zip

#### Due Diligence
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.

### CODE REVIEW

**Comment by connyduck** [comment]
It is not only a valid thing to do, it is the recommended thing to do. Lossless webps are supported since Android SDK 18. https://developer.android.com/studio/write/convert-webp

**Comment by OxygenCobalt** [comment]
Oh, I didn't know about this.  This seems good then @connyduck.

**Comment by OxygenCobalt** [comment]
Can you sign your commits @connyduck?

**Comment by connyduck** [comment]
Looks like a hassle. Why?

**Comment by OxygenCobalt** [comment]
I've configured the repository to only allow signed commits to be merged.

**Comment by OxygenCobalt** [comment]
I generally like to maintain as much authenticity in commits as I can, given that I sign all of my commits.

**Pull request merged**
