### PR TITLE
Use a theme background color for notification if no thumbnail available

### PR DESCRIPTION
**Pull request by Bnyro**
#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of changes

- The change only affects Android 13 and up!
- Currently, if you play a song that doesn't have a thumbnail, the default blue color is being used as a notification thumbnail. The PR changes that behavior, so that `colorPrimaryContainer` is used instead.
- That'll make the overall usage of the application theme more consistent.

#### Any additional information
- I have two concerns with this: 
* The current way to receive the context of the `MainActivity` isn't too clean, however using the `applicationContext` won't work because it isn't themed the same way so that no colors would be found.
* I'm not sure whether it wouldn't be a better idea to instead override the method in the `DescriptionAdapter` of the notification, but since that's not used currently I wasn't sure if there's a specific reason to avoid it.

#### APK testing
[app-debug.zip](https://github.com/OxygenCobalt/Auxio/files/11140493/app-debug.zip)

#### Due Diligence
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.

### CODE REVIEW

**Comment by OxygenCobalt** [comment]
I don't really get the point of this. When it comes to "external" code, I like to defer to the system as much as possible. See how the widget always defaults to Blue/Dynamic rather than reflecting the theme.

**Comment by OxygenCobalt** [comment]
Some other nitpicks:
- You don't need to resolve the activity. Obtaining `UISettings.accent` is better and will allow you to respond to accent changes easily.
- `BitmapProvider` is used not just in the notification. It also powers the widget and MediaSession. You probably want to make this more localized to `MediaSessionComponent`.

**Comment by Bnyro** [comment]
> I don't really get the point of this. When it comes to "external" code, I like to defer to the system as much as possible. See how the widget always defaults to Blue/Dynamic rather than reflecting the theme. I've generally found that trying to "port" Auxio's theming to SystemUI only results in endless bugs due to OEM variation.
>
I agree in general, however most if not all Android 13 ROMs use the new notification design, or if not at least the image as background color so that there shouldn't be any compatibility issues with this change. However, if you prefer so, we could also turn this into an option in the appearance settings which is disabled by default, however I'm not sure how much sense it would make to create preferences for such minor things. As always, in the end it's your project and your choice ;)

**Comment by OxygenCobalt** [comment]
Counterpoint: LG has not updated their SystemUI in years, but still updates to new android OS versions. It will still use the old notification design. Other OEMs may switch to a different "default" image that I'd like to remain consistent with, instead of just blue. Others might use the album cover in strange places that would look incredibly janky if a custom color was used. I simply do not feel comfortable with doing this.

**Comment by Bnyro** [comment]
Have you considered making this an option that is disabled by default? That way we would in fact use the ROMs default design as long as the user doesn't decide to prefer a difference behavior and there shouldn't be any negative impacts on the default user experience, while users of modern devices could indeed benefit.

**Comment by OxygenCobalt** [comment]
I've seen way too many other music players accumulate these "just in case" settings that simply add technical debt.

**Comment by Bnyro** [comment]
What other music players do is not relevant for this PR since no other music player has such an option. We already have options to set different notification actions (e.g. shuffle or repeat), adding another one for the background shouldn't be anything to be ashamed for.
If OEM compatibility is an issue, why does Auxio support dynamic colors then? Not all OEMs, e.g. LG apparently, do support them. Dynamic colors were implemented as an option, exactly the same thing would be aimed for with this preference :)

**Comment by OxygenCobalt** [comment]
Auxio has more agency with some system functionality than others. The `MediaSession` and `MediaStyle` APIs are so horribly designed that I usually try to keep the code as simple as I can. You can already see the mess of version-specific functionality that I have to deal with regarding the notification action setting, but inertia and general user demand prevents me from doing this. Here, I can already see the piles of edge-cases this will cause, and I really do not see the purpose of it in the slightest.

**Pull request closed without merging**
