### PR TITLE
Cover art carousel on playback fragment

### PR DESCRIPTION
**Pull request by Koitharu**
#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of changes
Like in  #496 but with ViewPager2

#### Fixes the following issues
#94 

#### Any additional information

https://github.com/OxygenCobalt/Auxio/assets/8948226/fec56825-17cd-471f-84e5-f95f50970048

#### APK testing

[app-debug.zip](https://github.com/OxygenCobalt/Auxio/files/11990358/app-debug.zip)

#### Due Diligence
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.

### CODE REVIEW

**Comment by OxygenCobalt** [comment]
Thanks for this @Koitharu! I never even knew that ViewPager2 allowed plain-old RecyclerView adapters. This probably resolves the visual bug I ran against earlier, but I'll confirm by individual testing. If this is okay, I'll merge it as soon as the current `dev` changes are available in-release. Feel free to ignore the failing CI build, I'm still working on that.

I would request one thing: Perhaps the title/artist/album could also scroll with the album cover. That would be a little more visually cohesive. I won't require this though since I can easily do it from my end.

**Comment by jf916** [comment]
This addition is perfect I hope that this can be added to the main repo soon

**Comment by Koitharu** [comment]
There is only a small issue: you cannot collapse the payback panel by swiping down on the ViewPager. So I guess increasing it's height (by including track information) might not be a good idea

**Comment by OxygenCobalt** [comment]
> There is only a small issue: you cannot collapse the payback panel by swiping down on the ViewPager. So I guess increasing it's height (by including track information) might not be a good idea

Well, this is really bad @Koitharu. I won't be able to accept this in it's current form without a fix for this. I'll go and fix it myself, since it probably requires tracing low-level view logic @Koitharu.

**Comment by OxygenCobalt** [comment]
Fixed that vertical scrolling issue, can go ahead with extending the pager to all song information.

**Comment by OxygenCobalt** [comment]
Fixed that vertical scrolling issue, can go ahead with extending the pager to all song information @Koitharu.

**Comment by Koitharu** [comment]
I also added some small improvements, I hope you'll find it usefull

**Comment by jf916** [comment]
I cannot find any problems with this

**Comment by OxygenCobalt** [comment]
I'll play around with this more when I get the time @Koitharu. I'm very busy with non-Auxio projects right now.

**Comment by jf916** [comment]
It has been 2 weeks. Why has this not been added yet?

**Comment by OxygenCobalt** [comment]
I am extremely busy @jf916. Additionally, I tend to limit how much "new" stuff appears in every major version so the process of patching regressions is less overwhelming, so this likely won't be merged for 3.2.0.

**Comment by jf916** [comment]
Ok

**Comment by OxygenCobalt** [comment]
I'll continue to debug this, expect it to arrive in like 3.3.0.

**Pull request merged**
