### PR TITLE
Permission documentation

### PR DESCRIPTION
**Pull request by offa**
Permission documentation added. 

Todo: What's `ACCESS_NETWORK_STATE` used for?

**What is it?**
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [x] Meta improvement to the project (dev facing)

**Description of changes**

Document permission required.

**Fixes the following issues**

/ 

**Any additional information**

/

**APK testing** 

/

**Due Diligence**

- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md) and [Accepted additions & Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md).

### CODE REVIEW

**Comment by OxygenCobalt** [comment]
AFAIK, `ACCESS_NETWORK_STATE` is a part of androidx or ExoPlayer. Not sure how to turn it off.

**Comment by offa** [comment]
There's a related issue here: https://github.com/google/ExoPlayer/issues/6019

It seems possible to revoke the permission by manifest (example included in the issue).

**Comment by OxygenCobalt** [comment]
Got it. I'll try pushing a commit removing the `ACCESS_NETWORK_STATE` perm from the in-progress README.

**Comment by offa** [comment]
Nice! :+1:

**Pull request merged**
