### PR TITLE
Implement bluetooth autoplay

### PR DESCRIPTION
**Pull request by seijikun**
#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Translation to:  (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of changes
See #235 

#### Fixes the following issues
#235 

#### Any additional information
I'm not quite sure whether `BluetoothConnectReceiver` does everything that's required to properly start playback yet.

#### APK testing
[app-debug.zip](https://github.com/OxygenCobalt/Auxio/files/9528571/app-debug.zip)

#### Due Diligence
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted additions & Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.

### CODE REVIEW

**Comment by seijikun** [comment]
I tried running `ktlint`, but got 1400 lint warnings on code that's not mine, so I'm not sure what to do here...

**Comment by OxygenCobalt** [comment]
Good work! I have a few nitpicks though:

First, some UI things:
- Say I connect my earbuds to my phone. Will this cause it to play exactly at the moment that the audio stream starts routing to my Earbuds? If this is the case, then I will gladly accept this feature. I've wanted to add this, but I'm only aware of the ACM broadcasts which didn't quite work to my desires, as playback would start before the audio stream was rerouted.
- I would prefer something like this to be unified with the existing "Headset Autoplay" feature. That only works for wired headsets, but if I were to extend it to Bluetooth, it would be via this setting.

Then, some issues I've noticed with the code:
- Avoid `Log.e(tag, "<function name>")` in favor of `logD("Recieved bluetooth A2DP request)`. This is just personal convention.
- I don't want to request permissions on startup. I would rather bind the permission check to the setting itself. I'll only query for permission when the user toggles the setting on. If the permission is revoked, the value will be set to false again.
- The service initialization is quite wonky. `RestoreState` is already started when the activity (and thus app) is created, and since broadcast receivers are only active when the app is alive, that call is redundant. Plus, `RestoreState` can take ~300ms or more, which could cause the app to crash as the service won't enter foreground in time. Wouldn't it be more correct to just start playing?
-I don't use ktlint. I use ktfmt. The errors are probably caused by the asterisk imports that have recently infested the codebase due to IntelliJ insanity.

**Comment by OxygenCobalt** [comment]
If possible, could you leave the branch open so I can push some commits of my own? I don't want to instruct you to do X when I can just write X myself.

**Comment by OxygenCobalt** [comment]
> As far as I understood it from the Android documentation, this action is only raised after the A2DP channel was correctly initialized - meaning that from this point onward, the audio route should already have been adapted towards that. From my testing, that's also what I saw in the log messages. The audio route manager told me: "Yay, bluetooth!" and then Auxio got woken up.

Okay. Sounds good.

> Yeah, that's exactly what I wanted to do. But the permission stuff is asynchronous and results are handled in the MainActivity's onPermissionRequestResult() method... I didn't know how to route that back to the SettingsFragment, so I gave up on that route.

`ActivityResultContract` is what I tend to use when requesting permissions from fragments. You can find an example on the `MainFragment.kt` file.

> I may be misunderstanding something, but as far as I understand it - the way I implemented it now (intent-filter in AndroidManifest.xml), this works if the app is dead. The way it's implemented now, the activity isn't started (I just confirmed this with a log message in MainActivity::onStart()). Only the PlaybackService is started. So I had to replicate what the MainActivity normally does to initialize everything.

That implies that my other intent filer (The media button one) also works if the app is dead. As far as I am aware, it doesn't. And if it did, I don't really like that because of the time it takes to restore the state.

I feel like something like this would be more appropriate:
```
if (playbackManager.song != null) { // Is there anything to even play?
    playbackManager.changePlaying(true)
}
```

An app going from dead -> foreground service is only going to get harder and harder as android versions go on, so this is largely a defensive measure.

**Comment by OxygenCobalt** [comment]
Oh, and another thing I forgot. Cold-starting Auxio like that will also not work how you expect since the music loading process is in another service and also needs to be ran. Again, this is why I don't do this.

**Comment by seijikun** [comment]
> That implies that my other intent filer (The media button one) also works if the app is dead. As far as I am aware, it doesn't.

My guess is that there has to be an active MediaSession for the `android.intent.action.MEDIA_BUTTON` action to be broadcasted. So it only works if there is an active media player. Maybe if you install a second mediaplayer and press a media button, Auxio will attempt to spawn :thinking:

**Comment by OxygenCobalt** [comment]
Huh, maybe. But again, my point applies that I *really* don't want to make the broadcast receiver initialize the service. Far too many bugs.

**Comment by seijikun** [comment]
What would you suggest we do to maintain usability? (No interaction required).
I think we could spawn the player Activity with an additional parameter that tell it to start playing immediately.

**Comment by OxygenCobalt** [comment]
I think that's called a "trampoline", and it's also restricted from Android 12 onwards. 

Plus, you're assuming that there is a player activity, when really it's just fragments all the way down :).

**Comment by OxygenCobalt** [comment]
I think you're still running on older devleopment axioms. To have a working app in modern android, you have to accept that everything interesting should be done only when you have interaction. Gone are the days of apps starting themselves out of nowhere.

Note that you will still be able to have no-interaction autoplayback after the app is initially opened though.

**Comment by OxygenCobalt** [comment]
> I would call spawning a foreground service from a broadcast receiver pretty much an interaction. (You can't start a background service exactly for that reason).

I mean, differences in interpretation.

I'll go and push some new commits to the branch. You put in the effort of at least laying the groundwork for this feature, so I'll still merge your commit in.

**Comment by KraXen72** [comment]
> I would prefer something like this to be unified with the existing "Headset Autoplay" feature. That only works for wired headsets, but if I were to extend it to Bluetooth, it would be via this setting.

i'd vouch for this to be a separate setting: plugging in headphones is a deliberate action you 100% meant to do and thus can reliably expect music will start playing,
but with bluetooth, my headphones randomly connect to whatever device they were connected to before, so if i want to use them on my pc and i was listening to music on my phone, not only do i gotta re-connect bluetooth, i also have to deal with music that starts playing...

**Comment by OxygenCobalt** [comment]
Hey @seijikun, I've approved #244, which is basically a more general version of the autoplay functionality you want. I've began to architecture a way of cleverly unifying background tasks into a single service that should resolve the foreground delay issue and background starts.

This feature is still planned to be up-streamed into 3.0.0 in it's reduced form, but when I rework the service lifecycle it should enable the behavior you want.

**Review by OxygenCobalt — APPROVED** [review]

**Comment by OxygenCobalt** [comment]
This has been merged, albeit disabled for now until I get the permission workflow. Sadly, due to other changes with the scope of 3.0.0, I don't see this getting enabled exactly. The skeleton remains however to make implementing it easy eventually.

**Pull request merged**
